export const TOP_PRODUCT_SELLING_REQUEST = 'TOP_PRODUCT_SELLING_REQUEST';
export const TOP_PRODUCT_SELLING_SUCCESS = 'TOP_PRODUCT_SELLING_SUCCESS';
export const TOP_PRODUCT_SELLING_FAILURE = 'TOP_PRODUCT_SELLING_FAILURE';